### PR TITLE
Improve pillar templating documentation

### PR DESCRIPTION
**Pull request by lkubb**
### What does this PR do?
* Clarifies some descriptions regarding pillar templating
* Adds an important security gotcha regarding the Vault pillar module

### What issues does this PR fix or reference?
Ref: https://github.com/salt-extensions/saltext-vault/issues/35
Ref: https://github.com/saltstack/salt/issues/66189

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by lkubb** [comment]
@jtraub91 Does this address your concerns? Note the phrase you quoted in your issue has not been part of this repo for some time. I will submit a PR for Salt 3007.x after merging this one in.

**Comment by jtraub91** [comment]
@lkubb the fact that it's acknowledged in these issues and the wording is being improved is good enough for me 👍

As a side note, I don't really understand the approle vulnerability in that a "salt master can thus escalate its privileges". If you care to enlighten me, that'd be cool, but maybe I just need to test that; it's a been a while since I've used it.

**Comment by lkubb** [comment]
> @lkubb the fact that it's acknowledged in these issues and the wording is being improved is good enough for me 👍

👍

> As a side note, I don't really understand the approle vulnerability in that a "salt master can thus escalate its privileges".

When issuing AppRoles, the master has privileges to create AppRoles and assign any policies it wants to any AppRole on the mount it manages. It does not have privileges to create the policies though, so it can assign existing policies only and would need to guess their names. In most cases, this is also the case when issuing tokens.

In short: Since it distributes privileges it itself does not have, this can be used for privilege escalation.

The note was added because of https://github.com/salt-extensions/saltext-vault/issues/35.

**Comment by jtraub91** [comment]
@lkubb I'm still struggling to understand the documentation, potential risk of privilege escalation, and use-case for having the master issue approle tokens to salt minions. If you can share any more insight on how that all works, I'd appreciate it; but  also, I feel like you are incorrect when you say "In most cases, this is also the case when issuing tokens" re privilege escalation. In vault, child token policies can only be a subset of the parent (see https://github.com/hashicorp/vault/issues/1597), so there doesn't seem to be any risk of privilege escalation if setup properly.

**Comment by lkubb** [comment]
> I feel like you are incorrect when you say "In most cases, this is also the case when issuing tokens" re privilege escalation.

Thanks for questioning, it's been a while since I used tokens.

> In vault, child token policies can only be a subset of the parent (see [hashicorp/vault#1597](https://github.com/hashicorp/vault/issues/1597))

Usually yes, but with exceptions.

Depending on your usage pattern of Vault, it can be impractical for the master to hold all policies it must be able to assign at all times (I would have guessed this is the norm) - and it's always unnecessary. In theory, one could grant the master `sudo` privileges on `auth/token/create`, which breaks this rule completely and should be avoided. Instead, one should create a Token Role, which also breaks this rule, but still allows to limit the assignable policies (something that does not work with AppRoles in practice, so they are comparable to `sudo` on `auth/token/create` in this regard).

Note: Afair the kind of tokens you're referring to (child tokens) are bound to the parent token, which means if the parent expires, they expire as well. This can mean if your Salt master is down for some reason and its token expires, all your minions lose Vault access at once. Getting around this means creating orphan tokens, which again requires `sudo` or a Token Role.

> so there doesn't seem to be any risk of privilege escalation if setup properly.

With Token Roles, the Salt master can still escalate its own privileges, but you can limit the scope.

> I'm still struggling to understand the documentation, potential risk of privilege escalation, and use-case for having the master issue approle tokens to salt minions.

That's a very broad topic. If you have specific questions, I can try to answer them to the best of my knowledge.

Re use case: Implementing AppRoles was my initial driver for rewriting the Vault integration - I wanted to reduce the ridiculous overhead of Vault policy management. At the time, if you wanted to assign policies to minions dynamically and securely (pillar templating was unavailable and my first fix to that situation), the only way was by referencing the minion ID, which ends up requiring a lot of policies.

E.g. for `vault` pillar usage only, this meant creating as many policies as you had minions, all with the same content (and possibly duplicating secret data in different paths since you couldn't group minions):

```
# policy 'salt-minion-a'
path "salt/data/pillar/minion-a" {
    capabilities = ["read"]
}
```

```
# policy 'salt-minion-b'
path "salt/data/pillar/minion-b" {
    capabilities = ["read"]
}
```
etc.

AppRoles are associated with entities (tokens were not at the time, this might have changed in the meantime). These entities hold metadata, which can be referenced in templated Vault policies. So now, one can create a single policy `salt-minion` comprising all of the above:

```
path "salt/data/pillar/{{identity.entity.metadata.minion-id}}" {
    capabilities = ["read"]
}
```

In general, AppRoles permit to require two distinct factors for successful authentication - a single compromised distribution path is insufficient then (e.g. deploy role ID during instance initialization with Terraform or image building with Packer, deploy secret ID with Salt). This is not really valid for the current state of the extension since the master needs to be able to read both (an implementation is possible though).

**Comment by jtraub91** [comment]
> Depending on your usage pattern of Vault, it can be impractical for the master to hold all policies it must be able to assign at all times (I would have guessed this is the norm) - and it's always unnecessary. In theory, one could grant the master `sudo` privileges on `auth/token/create`, which breaks this rule completely and should be avoided. Instead, one should create a Token Role, which also breaks this rule, but still allows to limit the assignable policies (something that does not work with AppRoles in practice, so they are comparable to `sudo` on `auth/token/create` in this regard).
> 
> Note: Afair the kind of tokens you're referring to (child tokens) are bound to the parent token, which means if the parent expires, they expire as well. This can mean if your Salt master is down for some reason and its token expires, all your minions lose Vault access at once. Getting around this means creating orphan tokens, which again requires `sudo` or a Token Role.
> 

Well, an architecture I think that could make sense would be that the salt-master's token either never expires or has a long period (e.g. 1 year) per user preference, and only has the policies it needs to assign to minions attached to it, along with token creation capabilities. I can't see how the salt-master would be able to escalate it's privileges with this in place. Then the minions would only be able to be granted a subset of these policies which would be applied as defined/templated in salt configuration.

> 
> With Token Roles, the Salt master can still escalate its own privileges, but you can limit the scope.
> 

Could you explain or demo this? Or maybe you just mean if it were given sudo or something (which I would not advise)

> 
> Re use case: Implementing AppRoles was my initial driver for rewriting the Vault integration - I wanted to reduce the ridiculous overhead of Vault policy management. At the time, if you wanted to assign policies to minions dynamically and securely (pillar templating was unavailable and my first fix to that situation), the only way was by referencing the minion ID, which ends up requiring a lot of policies.
> 

I have used the vault integration before the 3007 changes, and I think adding pillar templating alone is a tremendous improvement. I agree, creating a policy per minion is too cumbersome and tedious, and templating with grains is insecure. Templating with pillar makes this secure and manageable in an elegant way.

However, while I understand using approle for salt-master may have benefits, I don't understand why you'd ever want the salt-master to _issue_ approle tokens to the salt minions. It seems that all or most scenarios can be handled with the salt-master issuing normal tokens, with templated policies.

That being said, I need to brush up on my knowledge of vault, and experiment with it some more. Also interested in continuing this conversation here or thru other channels. Cheers 🍻

**Comment by lkubb** [comment]
> Well, an architecture I think that could make sense would be that the salt-master's token either never expires or has a long period (e.g. 1 year) per user preference

This could work, but is a security issue in itself if you forget about long-lived tokens. One of the main points of the Vault architecture is automating periodic renewal instead of explicit revocation.

> and only has the policies it needs to assign to minions attached to it, along with token creation capabilities.

We're talking about the same thing from different angles. :) Token Roles allow you to only have token creation capabilities without the need for all policies you want to be able to assign to apply to yourself and be known beforehand verbatim. If a master performed privilege escalation using a properly configured Token Role, its most privileged state would equal the one you would start with when not using one. A leaked master token itself would not allow you to read minion pillars for example, you could only use it to issue such a token. This should also explain the following:

> I can't see how the salt-master would be able to escalate it's privileges with this in place.

... because the most escalated state is its default state in that case.

 
> > With Token Roles, the Salt master can still escalate its own privileges, but you can limit the scope.
> 
> Could you explain or demo this?

Strapped for time rn, but this might be of help: https://developer.hashicorp.com/vault/api-docs/auth/token#create-update-token-role

It's also mentioned briefly in the docs (which are more readable in the rendered state).

> However, while I understand using approle for salt-master may have benefits, I don't understand why you'd ever want the salt-master to _issue_ approle tokens to the salt minions. It seems that all or most scenarios can be handled with the salt-master issuing normal tokens, with templated policies.

Yes, most scenarios can be handled that way, but each method has different benefits and drawbacks. Vault is very flexible and specific use cases vary a lot.

> That being said, I need to brush up on my knowledge of vault, and experiment with it some more. Thanks for your reply and I'd be interested in continuing this conversation here or thru other channels. Cheers 🍻

Sure. :) Cheers!

**Pull request merged**
